"""make target_column nullable in model_fits

Revision ID: e0972cca4bcc
Revises: 75a253f883d5
Create Date: 2026-01-22 02:46:49.775235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0972cca4bcc'
down_revision: Union[str, Sequence[str], None] = '75a253f883d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_fits', schema=None) as batch_op:
        batch_op.alter_column('target_column',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('pipeline_versions', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'pipelines', ['pipeline_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pipeline_versions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('model_fits', schema=None) as batch_op:
        batch_op.alter_column('target_column',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
